@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IDataJobFactory {
    +DataJob(...) : IDataJob
    +DataJobRoot(...) : IDataJobRoot
  }

  interface IJobFactory
  interface IDataJob
  interface IDataJobRoot
}

package "TplQueue.Core" {
  class DataJobFactory {
    +Create(jobFactory) : IDataJobFactory
    +DataJob(...) : IDataJob
    +DataJobRoot(...) : IDataJobRoot
  }

  class "DataJob<TPayload>" as DataJobT
  class "DataJobRoot<TPayload>" as DataJobRootT
}

DataJobFactory ..|> IDataJobFactory
DataJobFactory *-- IJobFactory : uses
DataJobFactory ..> DataJobT : creates
DataJobFactory ..> DataJobRootT : creates
@enduml
