@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IQ
  interface IJobNode
  interface IJobRoot
}

package "TplQueue.Core" {
  interface IJobRootCommandAsync

  abstract class JobNodeBase

  class JobRoot {
    +Enqueue(queue, ct) : IQ
    +After(previousTasks) : IJobRoot
    +Create(...) : JobRoot
    +GetRetryPolicyFactory() : Func<IRetryPolicy>
  }
}

IJobRootCommandAsync --|> IJobRoot
JobRoot --|> JobNodeBase
JobRoot ..|> IJobRootCommandAsync
JobRoot ..> IQ : Enqueue()
JobRoot ..> IJobNode : After(...)
@enduml
