@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IJobNode
  interface IJobRoot
}

package "TplQueue.Core" {
  interface IJobGraphExpander {
    +ExpandGraph(jobRoot) : IReadOnlyList<IJobNode>
  }

  class JobGraphExpander {
    +Create() : IJobGraphExpander
    +ExpandGraph(jobRoot) : IReadOnlyList<IJobNode>
  }
}

JobGraphExpander ..|> IJobGraphExpander
JobGraphExpander ..> IJobRoot
JobGraphExpander ..> IJobNode
@enduml
