@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IJobRoot

  interface IFifoQ {
    +Enqueue(...) : IFifoQ
  }
}

package "TplQueue.Core" {
  abstract class QAbstract

  class JobRoot {
    +Create(...) : JobRoot
  }

  class FifoQ {
    +Create(...) : IFifoQ
    +Enqueue(...) : IFifoQ
  }
}

FifoQ --|> QAbstract
FifoQ ..|> IFifoQ
FifoQ ..> JobRoot : Create()
FifoQ ..> IJobRoot : Enqueue(jobRoot)
@enduml
