@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IQ
  interface IJob
  interface IJobNode
  interface IJobRoot
  interface IDataJob
  interface IDataJobRoot
  interface IPayload
}

package "TplQueue.Core" {
  abstract class "DataJobNodeBase<TPayload>" as DataJobNodeBaseT {
    +Id : Guid
    +Name : string
    +IsCompleted : bool
    +ExecutionStart : DateTime
    +ExecutionEnd : DateTime
    +ExecutionTime : TimeSpan
    +Status : TaskStatus
    +Dependencies : IReadOnlyCollection<IJobInfo>
    +Payload : TPayload
    +PayloadType : Type
    +CrossQueueId : Guid
    +PayloadHandlerKey : string
    +CopyInfo() : IJobInfo
    +GetInnerJob() : IJobNode
    +GetJobInfoDependencies() : IJobInfo[]
    +GetJobsBatch() : IJobNode[]
    +GetPayload() : object
    +GetDependentDataJobs() : IReadOnlyList<IDataJob>
    +GetRetryPolicyFactory() : Func<IRetryPolicy>
    +SetRoot(jobRoot) : void
    +WaitUntilFinishedAsync() : Task
    +Serialize(serializer) : string
  }

  class "DataJob<TPayload>" as DataJobT {
    +Create(job, payload) : DataJob<TPayload>
    +After(previousTasks) : IJob
  }

  class "DataJobRoot<TPayload>" as DataJobRootT {
    +CreateRoot(job, payload) : DataJobRoot<TPayload>
    +Enqueue(jobQ, ct) : IQ
    +After(previousTasks) : IJobRoot
  }
}

DataJobT --|> DataJobNodeBaseT
DataJobRootT --|> DataJobNodeBaseT

DataJobT ..|> IDataJob
DataJobRootT ..|> IDataJobRoot

DataJobNodeBaseT *-- IJobNode : inner job
DataJobNodeBaseT *-- IPayload : payload
@enduml
