@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IJobRootFactory {
    +JobRoot(...) : IJobRoot
  }

  interface IJobFactory {
    +Job(...) : IJob
  }

  interface IJob
  interface IJobRoot
}

package "TplQueue.Core" {
  class JobFactory {
    +Create() : IJobFactory
    +Job(...) : IJob
    +JobRoot(...) : IJobRoot
  }

  class Job
  class JobRoot
  class NoRetryPolicy <<static>>
}

IJobFactory --|> IJobRootFactory
JobFactory ..|> IJobFactory

JobFactory ..> Job : creates
JobFactory ..> JobRoot : creates
JobFactory ..> NoRetryPolicy : fallback
@enduml
