@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IParallelQ

  interface IParallelJobQAdapter {
    +GetInnerQ() : IParallelQ
  }
}

package "TplQueue.Core" {
  class ParallelQAdapter {
    +OnJobEventChanged : Func<IJobEvent, Task>
    +IsDisposed : bool
    +Name : string
    +MaxParallelism : int
    +RetryPolicyFactory : Func<IRetryPolicy>
    +Semaphore : SemaphoreSlim
    +QueueId : Guid
    +Dispose() : void
    +GetInnerQ() : IParallelQ
    +Enqueue(...) : IParallelQ
    +EnqueueFifo(...) : IParallelQ
    +ResumePolling() : void
    +Pause() : void
    +Wait() : Task
    +SetRetryPolicyFactory(retryPolicy) : IQ
    +Subscribe(observer) : IDisposable
  }

  class CacheQ
}

IParallelJobQAdapter --|> IParallelQ
ParallelQAdapter ..|> IParallelJobQAdapter
ParallelQAdapter *-- IParallelQ : wraps
CacheQ --|> ParallelQAdapter
@enduml
