@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IJob
  interface IJobNode
  interface IJobRoot
}

package "TplQueue.Core" {
  interface IJobNodeCommandAsync {
    +ExecuteAsync(ct) : Task<IJobNode>
    +Clear() : void
    +GetBatchJobCommands() : IReadOnlyCollection<IJobNodeCommandAsync>
  }

  interface IJobCommandAsync

  abstract class JobNodeBase {
    +Id : Guid
    +Name : string
    +IsCompleted : bool
    +Status : TaskStatus
    +ExecutionStart : DateTime
    +ExecutionEnd : DateTime
    +ExecutionTime : TimeSpan
    +Dependencies : IReadOnlyCollection<IJobInfo>
    +CrossQueueId : Guid
    +GetJobsBatch() : IJobNode[]
    +GetJobInfoDependencies() : IJobInfo[]
    +ExecuteAsync(ct) : Task<IJobNode>
    +WaitUntilFinishedAsync() : Task
    +CopyInfo() : IJobInfo
    +Clear() : void
    +GetRetryPolicyFactory() : Func<IRetryPolicy>
    +SetRoot(jobRoot) : void
    +GetBatchJobCommands() : IReadOnlyCollection<IJobNodeCommandAsync>
  }

  class Job {
    +MaxDependencyDepth : int
    +Create(...) : Job
    +After(previousTasks) : IJob
    +JobCommand(job) : IJobNodeCommandAsync
    +RunAction(...) : Func<CancellationToken, Task>
    +RunFunction(...) : Func<CancellationToken, Task>
  }

  class JobExtensions <<static>> {
    +Then(previous, next) : IJob
    +Then(previous, nextRoot) : IJobRoot
  }
}

IJobNodeCommandAsync --|> IJobNode
IJobCommandAsync --|> IJob

JobNodeBase ..|> IJobNodeCommandAsync
Job --|> JobNodeBase
Job ..|> IJobCommandAsync
JobExtensions ..> IJob
JobExtensions ..> IJobRoot
@enduml
