@startuml
top to bottom direction
skinparam linetype ortho
skinparam shadowing false
skinparam classAttributeIconSize 0
hide circle

package "TplQueue.Abstractions" <<External>> {
  interface IJobNode
}

package "TplQueue.Core" {
  class AsyncAutoResetEvent {
    +WaitAsync(cancellationToken = default) : Task
    +Set() : void
  }

  class "AsyncOrderedQueue<T>" as AsyncOrderedQueueT {
    +Enqueue(item, jobRootId, isFifo, queueId, cancellationToken) : bool
    +DequeueAsync(cancellationToken) : Task<(T, Guid, CancellationToken, bool)>
  }
}

AsyncOrderedQueueT *-- AsyncAutoResetEvent
AsyncOrderedQueueT ..> IJobNode
@enduml
